### ISSUE TITLE
Add vuepress style admonitions to blog markdown

### ISSUE THREAD

**Issue by pydanny** [pydanny/pydanny-v2#150]
In Vuepress this produces lovely results: 

```
!!! tip Cool
This is a tip.
!!!
```

Reference: https://friendlyuser.github.io/vuepress-theme-cool-starter/admonitions.html#examples

But in Vuepress Blog Markdown it doesn't do anything.

**Comment by pydanny** [comment]
This is a non-standard item and will make feed generation really hard.

**Comment by z3by** [comment]
maybe this could help https://vuepress.github.io/en/plugins/container/#installation
