### ISSUE TITLE
Must incorporate Disqus for comments

### ISSUE THREAD

**Issue by Scarletbegonias68** [pydanny/pydanny-v2#3]
Eventually move off Disqus
Possibly switch to GitHub issue powered comments

**Comment by z3by** [comment]
what do you think of utterance? check this out 
https://danyow.net/using-github-issues-for-blog-comments/
https://utteranc.es

**Comment by pydanny** [comment]
Fixed the disqus issue in b2e72a8bf3f467ab8a6b367d1770e90364ebbb7d

**Comment by pydanny** [comment]
@z3by For historical (before October 2019) blog posts we use disqus. After that we use Utterances (https://utteranc.es).

**Comment by pydanny** [comment]
What about https://vssue.js.org/?

**Comment by z3by** [comment]
@pydanny it seems better than utterances and has better Vue.js support!

**Comment by z3by** [comment]
but it requires the user to have a Github account! and that will prevent non-developers from commenting on non-technical Posts!
