### ISSUE TITLE
Existing URLs need to be honored, can use redirects

### ISSUE THREAD

**Issue by Scarletbegonias68** [pydanny/pydanny-v2#7]

**Comment by z3by** [comment]
what exactly do you mean by URLs? do you mean the URLs structure?

**Comment by pydanny** [comment]
Yes, URL structure.

In the old system https://www.pydanny.com/using-executable-code-outside-version-control.html exists.

In the new system it is currently listed at https://pydanny.netlify.com/_08-03-stop-using-executable-code-outside-version-control/

There needs to either be a 302 redirect or the URL for _08-03-stop-using-executable-code-outside-version-control/ must be adjusted to be https://www.pydanny.netlify.com/using-executable-code-outside-version-control.html

**Comment by z3by** [comment]
fixed please check 
* https://github.com/pydanny/pydanny-v2/commit/6b36ffeba75613fa57e54a9b04642bd56db241d0
* https://github.com/pydanny/pydanny-v2/commit/18ad1a14986c6d998c2dae55c11d02da836c304f

**Comment by pydanny** [comment]
Lovely!
